# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'document_manager.ui'
#
# Created: Thu Nov 18 13:40:15 2010
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DocManager(object):
    def setupUi(self, DocManager):
        DocManager.setObjectName(_fromUtf8("DocManager"))
        DocManager.resize(800, 400)
        self.verticalLayout_3 = QtGui.QVBoxLayout(DocManager)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(DocManager)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cmb_servers = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_servers.sizePolicy().hasHeightForWidth())
        self.cmb_servers.setSizePolicy(sizePolicy)
        self.cmb_servers.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_servers.setModelColumn(0)
        self.cmb_servers.setObjectName(_fromUtf8("cmb_servers"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmb_servers)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.tlw_db_list = ServersList(self.layoutWidget)
        self.tlw_db_list.setProperty(_fromUtf8("showDropIndicator"), False)
        self.tlw_db_list.setAlternatingRowColors(True)
        self.tlw_db_list.setRootIsDecorated(False)
        self.tlw_db_list.setItemsExpandable(False)
        self.tlw_db_list.setExpandsOnDoubleClick(False)
        self.tlw_db_list.setObjectName(_fromUtf8("tlw_db_list"))
        self.verticalLayout_2.addWidget(self.tlw_db_list)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_clean_views = QtGui.QToolButton(self.layoutWidget)
        self.btn_clean_views.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_clean_views.setObjectName(_fromUtf8("btn_clean_views"))
        self.horizontalLayout_3.addWidget(self.btn_clean_views)
        self.btn_compact_views = QtGui.QToolButton(self.layoutWidget)
        self.btn_compact_views.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_compact_views.setObjectName(_fromUtf8("btn_compact_views"))
        self.horizontalLayout_3.addWidget(self.btn_compact_views)
        self.btn_compact_db = QtGui.QToolButton(self.layoutWidget)
        self.btn_compact_db.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_compact_db.setObjectName(_fromUtf8("btn_compact_db"))
        self.horizontalLayout_3.addWidget(self.btn_compact_db)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_last_update = QtGui.QLabel(self.layoutWidget1)
        self.lbl_last_update.setObjectName(_fromUtf8("lbl_last_update"))
        self.horizontalLayout_4.addWidget(self.lbl_last_update)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_refresh_all = QtGui.QToolButton(self.layoutWidget1)
        self.btn_refresh_all.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_refresh_all.setObjectName(_fromUtf8("btn_refresh_all"))
        self.horizontalLayout_4.addWidget(self.btn_refresh_all)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.tlw_view_list = ServersList(self.layoutWidget1)
        self.tlw_view_list.setProperty(_fromUtf8("showDropIndicator"), False)
        self.tlw_view_list.setAlternatingRowColors(True)
        self.tlw_view_list.setRootIsDecorated(False)
        self.tlw_view_list.setItemsExpandable(False)
        self.tlw_view_list.setExpandsOnDoubleClick(False)
        self.tlw_view_list.setObjectName(_fromUtf8("tlw_view_list"))
        self.verticalLayout.addWidget(self.tlw_view_list)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_compact = QtGui.QToolButton(self.layoutWidget1)
        self.btn_compact.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_compact.setObjectName(_fromUtf8("btn_compact"))
        self.horizontalLayout_2.addWidget(self.btn_compact)
        self.btn_ping = QtGui.QToolButton(self.layoutWidget1)
        self.btn_ping.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ping.setObjectName(_fromUtf8("btn_ping"))
        self.horizontalLayout_2.addWidget(self.btn_ping)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(DocManager)
        QtCore.QMetaObject.connectSlotsByName(DocManager)

    def retranslateUi(self, DocManager):
        DocManager.setWindowTitle(QtGui.QApplication.translate("DocManager", "DB Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DocManager", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clean_views.setText(QtGui.QApplication.translate("DocManager", "Cleanup views", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_compact_views.setText(QtGui.QApplication.translate("DocManager", "Compact views", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_compact_db.setText(QtGui.QApplication.translate("DocManager", "Compact db", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DocManager", "Last refresh:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_last_update.setText(QtGui.QApplication.translate("DocManager", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_refresh_all.setText(QtGui.QApplication.translate("DocManager", "Refresh all", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_compact.setText(QtGui.QApplication.translate("DocManager", "Compact", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ping.setText(QtGui.QApplication.translate("DocManager", "Ping", None, QtGui.QApplication.UnicodeUTF8))

from list_prototype import ServersList