# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_task.ui'
#
# Created: Tue Jan 18 15:59:51 2011
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_New_Task_Form(object):
    def setupUi(self, New_Task_Form):
        New_Task_Form.setObjectName(_fromUtf8("New_Task_Form"))
        New_Task_Form.setWindowModality(QtCore.Qt.NonModal)
        New_Task_Form.resize(807, 418)
        self.verticalLayout = QtGui.QVBoxLayout(New_Task_Form)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.box_source = QtGui.QGroupBox(New_Task_Form)
        self.box_source.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.box_source.setFont(font)
        self.box_source.setFlat(False)
        self.box_source.setObjectName(_fromUtf8("box_source"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.box_source)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.rdb_localsource = QtGui.QRadioButton(self.box_source)
        self.rdb_localsource.setChecked(True)
        self.rdb_localsource.setObjectName(_fromUtf8("rdb_localsource"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.rdb_localsource)
        self.cmb_localsource = QtGui.QComboBox(self.box_source)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_localsource.sizePolicy().hasHeightForWidth())
        self.cmb_localsource.setSizePolicy(sizePolicy)
        self.cmb_localsource.setObjectName(_fromUtf8("cmb_localsource"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmb_localsource)
        self.rdb_remotesource = QtGui.QRadioButton(self.box_source)
        self.rdb_remotesource.setObjectName(_fromUtf8("rdb_remotesource"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.rdb_remotesource)
        self.txt_remotesource = QtGui.QLineEdit(self.box_source)
        self.txt_remotesource.setEnabled(False)
        self.txt_remotesource.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_remotesource.setFrame(True)
        self.txt_remotesource.setObjectName(_fromUtf8("txt_remotesource"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_remotesource)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.box_source)
        self.box_target = QtGui.QGroupBox(New_Task_Form)
        self.box_target.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.box_target.setFont(font)
        self.box_target.setFlat(False)
        self.box_target.setObjectName(_fromUtf8("box_target"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.box_target)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.rdb_localtarget = QtGui.QRadioButton(self.box_target)
        self.rdb_localtarget.setChecked(True)
        self.rdb_localtarget.setObjectName(_fromUtf8("rdb_localtarget"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.rdb_localtarget)
        self.cmb_localtarget = QtGui.QComboBox(self.box_target)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_localtarget.sizePolicy().hasHeightForWidth())
        self.cmb_localtarget.setSizePolicy(sizePolicy)
        self.cmb_localtarget.setObjectName(_fromUtf8("cmb_localtarget"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmb_localtarget)
        self.rdb_remotetarget = QtGui.QRadioButton(self.box_target)
        self.rdb_remotetarget.setObjectName(_fromUtf8("rdb_remotetarget"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.rdb_remotetarget)
        self.txt_remotetarget = QtGui.QLineEdit(self.box_target)
        self.txt_remotetarget.setEnabled(False)
        self.txt_remotetarget.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_remotetarget.setObjectName(_fromUtf8("txt_remotetarget"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_remotetarget)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout.addWidget(self.box_target)
        self.box_additions = QtGui.QGroupBox(New_Task_Form)
        self.box_additions.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.box_additions.setFont(font)
        self.box_additions.setFlat(False)
        self.box_additions.setObjectName(_fromUtf8("box_additions"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.box_additions)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_4 = QtGui.QLabel(self.box_additions)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txt_proxy = QtGui.QLineEdit(self.box_additions)
        self.txt_proxy.setObjectName(_fromUtf8("txt_proxy"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_proxy)
        self.label_5 = QtGui.QLabel(self.box_additions)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmb_filters = QtGui.QComboBox(self.box_additions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_filters.sizePolicy().hasHeightForWidth())
        self.cmb_filters.setSizePolicy(sizePolicy)
        self.cmb_filters.setEditable(True)
        self.cmb_filters.setObjectName(_fromUtf8("cmb_filters"))
        self.horizontalLayout_4.addWidget(self.cmb_filters)
        self.btn_getfilters = QtGui.QToolButton(self.box_additions)
        self.btn_getfilters.setObjectName(_fromUtf8("btn_getfilters"))
        self.horizontalLayout_4.addWidget(self.btn_getfilters)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtGui.QLabel(self.box_additions)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.txt_query = QtGui.QLineEdit(self.box_additions)
        self.txt_query.setObjectName(_fromUtf8("txt_query"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_query)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout.addWidget(self.box_additions)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_save = QtGui.QPushButton(New_Task_Form)
        self.btn_save.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_cancel = QtGui.QPushButton(New_Task_Form)
        self.btn_cancel.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(New_Task_Form)
        QtCore.QMetaObject.connectSlotsByName(New_Task_Form)

    def retranslateUi(self, New_Task_Form):
        New_Task_Form.setWindowTitle(QtGui.QApplication.translate("New_Task_Form", "Add New Task", None, QtGui.QApplication.UnicodeUTF8))
        self.box_source.setTitle(QtGui.QApplication.translate("New_Task_Form", "Replicate changes from", None, QtGui.QApplication.UnicodeUTF8))
        self.rdb_localsource.setText(QtGui.QApplication.translate("New_Task_Form", "Local database:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdb_remotesource.setText(QtGui.QApplication.translate("New_Task_Form", "Remote database:", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_remotesource.setText(QtGui.QApplication.translate("New_Task_Form", "http://", None, QtGui.QApplication.UnicodeUTF8))
        self.box_target.setTitle(QtGui.QApplication.translate("New_Task_Form", "Replicate changes to", None, QtGui.QApplication.UnicodeUTF8))
        self.rdb_localtarget.setText(QtGui.QApplication.translate("New_Task_Form", "Local database:", None, QtGui.QApplication.UnicodeUTF8))
        self.rdb_remotetarget.setText(QtGui.QApplication.translate("New_Task_Form", "Remote database:", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_remotetarget.setText(QtGui.QApplication.translate("New_Task_Form", "http://", None, QtGui.QApplication.UnicodeUTF8))
        self.box_additions.setTitle(QtGui.QApplication.translate("New_Task_Form", "Additions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("New_Task_Form", "Proxy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("New_Task_Form", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_getfilters.setText(QtGui.QApplication.translate("New_Task_Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("New_Task_Form", "Query:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("New_Task_Form", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("New_Task_Form", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
